## =========================
## docker-compose.yml
## =========================
services:
  db:
    image: dockerhub.timeweb.cloud/library/postgres:16-alpine
    container_name: project-db
    environment:
      POSTGRES_DB: aiwardrobe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    image: ghcr.io/luckx16/ai-wardrobe-server:latest
    container_name: project-server
    environment:
      NODE_ENV: production
      PORT: '4000'
      DATABASE_URL_PROD: postgresql://postgres:postgres@db:5432/aiwardrobe
      JWT_ACCESS: ${JWT_ACCESS}
      JWT_REFRESH: ${JWT_REFRESH}
      GIGACHAT_CREDENTIALS: ${GIGACHAT_CREDENTIALS}
      GIGACHAT_SCOPE: ${GIGACHAT_SCOPE}
    ports:
      - '4000:4000'
    volumes:
      - uploads_data:/app/src/public/uploads
      - ./.env:/app/.env:ro
    depends_on:
      db:
        condition: service_healthy
    command: ['sh', '-c', 'npx sequelize-cli db:migrate; node ./src/app.js']
    restart: unless-stopped

  client:
    image: ghcr.io/luckx16/ai-wardrobe-client:latest
    container_name: project-client
    environment:
      NODE_ENV: production
      PORT: '3000'
    depends_on:
      - server
    ports:
      - '3000:3000'
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  caddy_data:
  uploads_data:
  db_data:
