## =========================
## docker-compose.yml
## =========================
services:
  server:
    image: luckx16/ai-wardrobe-server:latest
    container_name: project-server
    environment:
      NODE_ENV: production
      PORT: '4000'
      DATABASE_URL_PROD: ${POSTGRES_URL_PROD}
      JWT_ACCESS: ${JWT_ACCESS}
      JWT_REFRESH: ${JWT_REFRESH}
      GIGACHAT_CREDENTIALS: ${GIGACHAT_CREDENTIALS}
      GIGACHAT_SCOPE: ${GIGACHAT_SCOPE}
    expose:
      - '4000'
    volumes:
      - uploads_data:/app/src/public/uploads
    command: ['sh', '-c', 'npx sequelize-cli db:migrate && node ./src/app.js']
    restart: unless-stopped

  client:
    image: luckx16/ai-wardrobe-client:latest
    container_name: project-client
    environment:
      NODE_ENV: production
      PORT: '3000'
    depends_on:
      - server
    expose:
      - '3000'
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  caddy_data:
  uploads_data:
